version: '3'

services:
  db:
    image: 'mongo'
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
  app:
    image: app_node
    build: ./app
    container_name: app
    ports:
      - '8080:8080'
    networks:
      - default